import type { AppData } from "./types";

export const initialData: AppData = {
  afdelingen: [
    {
      id: "afd-snijden",
      title: "Snijden",
      omschrijving: "Machines voor snijden, portioneren en voorbereiden.",
      actief: true,
      volgorde: 1,
    },
    {
      id: "afd-verpakken",
      title: "Verpakken",
      omschrijving: "Werkplekken voor vacumeren, etiketteren en verpakken.",
      actief: true,
      volgorde: 2,
    },
    {
      id: "afd-koeling",
      title: "Koeling",
      omschrijving: "Koelcellen, klimaatcontrole en registratie.",
      actief: true,
      volgorde: 3,
    },
  ],
  personen: [
    {
      id: "per-nathan",
      title: "Nathan",
      email: "nathan@example.com",
      functie: "Beheerder",
      afdelingId: "afd-snijden",
      actief: true,
    },
    {
      id: "per-operator",
      title: "Werkvloer operator",
      email: "operator@example.com",
      functie: "Operator",
      afdelingId: "afd-verpakken",
      actief: true,
    },
  ],
  leveranciers: [
    {
      id: "lev-techservice",
      title: "TechService BV",
      contactpersoon: "Servicebalie",
      email: "service@example.com",
      telefoon: "010-0000000",
      opmerking: "Algemene onderhoudspartner voor machines.",
    },
    {
      id: "lev-koeltechniek",
      title: "Koeltechniek Noord",
      contactpersoon: "Planning",
      email: "planning@example.com",
      telefoon: "020-0000000",
      opmerking: "Contact voor koelinstallaties en storingen.",
    },
  ],
  machines: [
    {
      id: "mac-snijder-01",
      title: "Snijmachine 01",
      afdelingId: "afd-snijden",
      leverancierId: "lev-techservice",
      verantwoordelijkeId: "per-nathan",
      omschrijving: "Hoofdmachine voor dagelijks snijwerk.",
      status: "Operationeel",
      serieNummer: "SN-2024-001",
      aankoopdatum: "2024-03-15",
      garantieVerloopdatum: "2027-03-15",
      afbeeldingUrl: "",
      actief: true,
    },
    {
      id: "mac-vacuum-01",
      title: "Vacumeermachine 01",
      afdelingId: "afd-verpakken",
      leverancierId: "lev-techservice",
      verantwoordelijkeId: "per-operator",
      omschrijving: "Vacumeren van verpakte producten.",
      status: "Onderhoud nodig",
      serieNummer: "VAC-2023-118",
      aankoopdatum: "2023-09-01",
      garantieVerloopdatum: "2026-09-01",
      afbeeldingUrl: "",
      actief: true,
    },
    {
      id: "mac-koelcel-01",
      title: "Koelcel 01",
      afdelingId: "afd-koeling",
      leverancierId: "lev-koeltechniek",
      verantwoordelijkeId: "per-nathan",
      omschrijving: "Opslag en temperatuurbeheersing.",
      status: "Operationeel",
      serieNummer: "KOEL-01",
      aankoopdatum: "2022-01-10",
      garantieVerloopdatum: "2025-01-10",
      afbeeldingUrl: "",
      actief: true,
    },
  ],
  onderhoud: [
    {
      id: "ond-snijder-check",
      title: "Mescontrole en reiniging",
      machineId: "mac-snijder-01",
      datumGepland: "2026-07-01",
      datumUitgevoerd: "",
      typeOnderhoud: "Preventief",
      verantwoordelijkeId: "per-nathan",
      verantwoordelijkeType: "Persoon",
      verantwoordelijkeRefId: "per-nathan",
      leverancierId: "lev-techservice",
      status: "Gepland",
      herhaling: "Maandelijks",
      herhalingWeekdag: "Maandag",
      herhalingTot: "2026-12-31",
      automatischOpnieuwPlannen: true,
      opmerking: "Controleer messen, kap en veiligheidsschakelaar.",
    },
    {
      id: "ond-vacuum-rubber",
      title: "Rubber vervangen",
      machineId: "mac-vacuum-01",
      datumGepland: "2026-06-28",
      datumUitgevoerd: "",
      typeOnderhoud: "Correctief",
      verantwoordelijkeId: "per-operator",
      verantwoordelijkeType: "Leverancier",
      verantwoordelijkeRefId: "lev-techservice",
      leverancierId: "lev-techservice",
      status: "In proces",
      herhaling: "Geen",
      herhalingWeekdag: "Maandag",
      herhalingTot: "",
      automatischOpnieuwPlannen: false,
      opmerking: "Seal lijkt niet overal gelijkmatig.",
    },
  ],
  storingen: [
    {
      id: "sto-vacuum-seal",
      title: "Sealrand onregelmatig",
      machineId: "mac-vacuum-01",
      datum: "2026-06-20",
      melderId: "per-operator",
      type: "Storing",
      prioriteit: "Hoog",
      status: "Open",
      omschrijving: "Bij meerdere verpakkingen sluit de rand niet goed.",
      oplossing: "",
    },
  ],
  documenten: [
    {
      id: "doc-snijder-handleiding",
      title: "Handleiding snijmachine",
      machineId: "mac-snijder-01",
      documentType: "Handleiding",
      omschrijving: "Gebruikershandleiding en veiligheidsinstructies.",
      vervaldatum: "",
      actief: true,
      url: "#",
    },
    {
      id: "doc-koelcel-keuring",
      title: "Laatste koelcelkeuring",
      machineId: "mac-koelcel-01",
      documentType: "Keuring",
      omschrijving: "Voorbeelddocument voor latere SharePoint-bibliotheek.",
      vervaldatum: "2027-01-10",
      actief: true,
      url: "#",
    },
  ],
};
